name: Build Firmware

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          idf_version: 'latest'
          idf_path: ${{ github.workspace }}/esp-idf

      - name: Build the project
        run: |
          cd ${{ github.workspace }}
          idf.py build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware.bin
